### ISSUE TITLE
Minimal Linode API Token Permissions?

### ISSUE THREAD

**Issue by igorbrigadir** [slicen/cert-manager-webhook-linode#4]
What are the minimal permissions that are required for the token? There's: 

Access  | None  | Read Only  | Read Write  
-- | -- | -- | --
Account |   |   |  
Domains |   |   |  
Events |   |   |  
Images |   |   |  
IPs |   |   |  
Kubernetes |   |   |  
Linodes |   |   |  
Longview |   |   |  
NodeBalancers |   |   |  
Object Storage |   |   |  
StackScripts |   |   |  
Volumes

I'm guessing it will need read access to domains? Account too?

**Comment by JonathanATyler** [comment]
Should only need Domains R/W so it can update the domain txt records. That's all I have and it works well.

**Comment by igorbrigadir** [comment]
I forgot i left this open, yes - only R/W for Domains is enough!
